name: 'Pull Request Validation'
description: 'Validate pull requests against defined ruleset.'
author: 'TRIMIT Group'
inputs:
  branch_main:
    description: 'Name of your main branch (default: main)'
    default: 'main'
  branch_develop:
    description: 'Name of your develop branch (default: develop)'
    default: 'develop'
  prefix_feature:
    description: 'Prefix for feature branches (default: feature/)'
    default: 'feature/'
  prefix_hotfix:
    description: 'Prefix for hotfix branches (default: hotfix/)'
    default: 'hotfix/'
  prefix_align:
    description: 'Prefix for alignment branches (default: align/)'
    default: 'align/'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'purple'